==========================================
SLURM_JOB_ID = 332811
SLURM_NODELIST = gnode36
SLURM_JOB_GPUS = 1,2
==========================================
=> creating model 'resnet'
True
the number of model parameters: 2073556
Traceback (most recent call last):
  File "train.py", line 426, in <module>
    main()
  File "train.py", line 201, in main
    train_loss = train(train_loader, model, criterion, optimizer, epoch)
  File "train.py", line 256, in train
    output = model(input)
  File "/home/sandeep.nagar/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sandeep.nagar/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/sandeep.nagar/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/sandeep.nagar/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/sandeep.nagar/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/sandeep.nagar/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/sandeep.nagar/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sandeep.nagar/seeds_project/CutMix-PyTorch-master/resnet.py", line 154, in forward
    x = self.layer1(x)
  File "/home/sandeep.nagar/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sandeep.nagar/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/sandeep.nagar/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sandeep.nagar/seeds_project/CutMix-PyTorch-master/resnet.py", line 69, in forward
    out = self.conv2(out)
  File "/home/sandeep.nagar/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sandeep.nagar/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/sandeep.nagar/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 10.92 GiB total capacity; 10.06 GiB already allocated; 67.00 MiB free; 10.17 GiB reserved in total by PyTorch)

